services:
  app:
    build:
      context: .
    volumes:
      - .:/app
    command: uvicorn main:app --host=0.0.0.0 --reload
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql+asyncpg://rsvp:r2d2@postgres/rsvp
      - LLM_MODEL=groq/mixtral-8x7b-32768
      - GROQ_API_KEY
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=r2d2
      - POSTGRES_DB=rsvp
      - POSTGRES_USER=rsvp
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
