"""field changes

Revision ID: 45ddbdefbec8
Revises: 9161a0588967
Create Date: 2024-07-02 09:24:09.589656

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "45ddbdefbec8"
down_revision: Union[str, None] = "9161a0588967"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_entries_path", table_name="entries")
    op.create_index(op.f("ix_entries_path"), "entries", ["path"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_entries_path"), table_name="entries")
    op.create_index("ix_entries_path", "entries", ["path"], unique=False)
    # ### end Alembic commands ###
