"""reading progress

Revision ID: 5764d739ac62
Revises: 01cdbf12b631
Create Date: 2024-07-07 05:38:21.634480

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5764d739ac62"
down_revision: Union[str, None] = "01cdbf12b631"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reading_progresses",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=True),
        sa.Column("chapter_index", sa.Integer(), nullable=True),
        sa.Column("word_index", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reading_progresses_id"), "reading_progresses", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reading_progresses_id"), table_name="reading_progresses")
    op.drop_table("reading_progresses")
    # ### end Alembic commands ###
