"""more fields to ramp up and down speed

Revision ID: 745e028c5ef9
Revises: 75046ca1c761
Create Date: 2024-07-07 11:23:24.754605

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "745e028c5ef9"
down_revision: Union[str, None] = "75046ca1c761"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reading_configs", sa.Column("ramp_step", sa.Integer(), nullable=True)
    )
    op.add_column("reading_configs", sa.Column("step_ups", sa.Integer(), nullable=True))
    op.add_column(
        "reading_configs", sa.Column("step_downs", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reading_configs", "step_downs")
    op.drop_column("reading_configs", "step_ups")
    op.drop_column("reading_configs", "ramp_step")
    # ### end Alembic commands ###
