"""reading progress word index nullable

Revision ID: 75046ca1c761
Revises: 5764d739ac62
Create Date: 2024-07-07 09:05:11.094109

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "75046ca1c761"
down_revision: Union[str, None] = "5764d739ac62"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
