"""updated at for progress

Revision ID: 976c3a458b54
Revises: 83a73ccd689f
Create Date: 2024-10-16 05:46:19.907895

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "976c3a458b54"
down_revision: Union[str, None] = "83a73ccd689f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reading_progresses",
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reading_progresses", "updated_at")
    # ### end Alembic commands ###
