"""sprint count column at backend

Revision ID: af75e7b5a8b6
Revises: f3762f50666f
Create Date: 2024-08-06 06:54:51.689585

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "af75e7b5a8b6"
down_revision: Union[str, None] = "f3762f50666f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reading_configs", sa.Column("sprint_count", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reading_configs", "sprint_count")
    # ### end Alembic commands ###
